services:
  - type: web
    name: fastapi-order-portal
    env: python
    plan: free

    pythonVersion: 3.11.9

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: SESSION_SECRET
        generateValue: true
